global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: payment-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - payment-gateway:8080
